backend:
  name: github
  repo: zohaibTariq6533/Hugo-Snortimmerwerken
  branch: main  
  auth_type: pkce
  app_id: Ov23liCCPh5APDx73cOR # adjust if your repo uses "master"

media_folder: "static/uploads"   # actual folder in repo
public_folder: "/uploads"        # how Hugo serves them
load_config_file: true
collections:

  # Homepage content (index.md)
  - name: "homepage"
    label: "Homepage"
    files:
      - label: "Hero Section"
        name: "index"
        file: "content/_index.md"   # Hugo homepage is usually `_index.md`, adjust if yours is just index.md
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "date", label: "Date", widget: "datetime" }
          - { name: "draft", label: "Draft", widget: "boolean", default: false }
          - { name: "hero_section", label: "Hero Section", widget: "string" }
          - { name: "hero_section2", label: "Hero Section 2", widget: "string" }
          - { name: "sub_heading", label: "Sub Heading", widget: "text" }
          - { name: "pricing", label: "Pricing", widget: "string" }
          - { name: "hero_image", label: "Hero Image", widget: "image", choose_url: false, media_folder: "static/uploads/Hero", public_folder: "/uploads/Hero" }
