backend:
  name: github
  repo: zohaibTariq6533/Hugo-Snortimmerwerken
  branch: main  
  auth_type: pkce
  app_id: Ov23liCCPh5APDx73cOR # adjust if your repo uses "master"

media_folder: "static/uploads"   # actual folder in repo
public_folder: "/uploads"        # how Hugo serves them
load_config_file: true
collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "content/_index.md"
        label: "Homepage Content"
        name: "homepage_content"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "date", label: "Date", widget: "datetime" }
          - { name: "draft", label: "Draft", widget: "boolean", default: false }

          # Hero Section
          - label: "Hero Section"
            name: "hero_section_group"
            widget: "object"
            fields:
              - { name: "hero_section", label: "Hero Section heading", widget: "string" }
              - { name: "hero_section2", label: "Hero Section colored", widget: "string" }
              - { name: "sub_heading", label: "Sub Heading", widget: "text" }
              - { name: "label1", label: "label Heading", widget: "string" }
              - { name: "label2", label: "label Text", widget: "string" }
              - { name: "hero_button1", label: "Button 1", widget: "string" }
              - { name: "hero_button1_number", label: "Number for button", widget: "number" }
              - { name: "hero_button2", label: "Button 2", widget: "string" }
              - { name: "no_of_reviews", label: "Total Reviews", widget: "number" }
              - { name: "review", label: "Review", widget: "text" }
              - { name: "reviewed_by", label: "Reviewed By", widget: "string" }
              - { name: "info_heading1", label: "Info heading 1", widget: "string" }
              - { name: "info_text1", label: "Info Text 1", widget: "string" }
              - { name: "info_heading2", label: "Info heading 2", widget: "string" }
              - { name: "info_text2", label: "Info Text 2", widget: "string" }
              - { name: "hero_image", label: "Hero Image", widget: "image", choose_url: false, media_folder: "/static/uploads/hero", public_folder: "/uploads/hero" }

          # Project Section
          - label: "Project Section"
            name: "project_section_group"
            widget: "object"
            fields:
              - { name: "project_section_title", label: "Project Heading", widget: "string" }
              - { name: "project_subheading", label: "Project Subheading", widget: "string" }
              - label: "Project Cards"
                name: "project_cards"
                widget: "list"
                min: 4
                max: 4
                summary: "{{fields.heading}}"
                fields:
                  - { name: "image", label: "Card Image", widget: "image", choose_url: false, media_folder: "/static/uploads/projects-img", public_folder: "/uploads/projects-img" }
                  - { name: "heading", label: "Card Heading", widget: "string" }
                  - { name: "description", label: "Card Description", widget: "text" }
                  - label: "Points"
                    name: "points"
                    widget: "list"
                    field: { name: "point", label: "Point", widget: "string" }
          - label: "Pricing Section"
            name: "pricing_section"
            widget: "object"
            fields:
              - { name: "pricing_title", label: "Pricing Title", widget: "string" }
              - label: "Pricing Cards"
                name: "pricing_cards"
                widget: "list"
                fields:
                  - { name: "title", label: "Card Title", widget: "string" }
                  - { name: "price", label: "Price", widget: "string" }
                  - { name: "duration", label: "Duration", widget: "string" }
                  - { name: "features", label: "Features", widget: "list", field: { label: "Feature", name: "feature", widget: "string" } }
              - { name: "button_title", label: "Button Title", widget: "string" }
          - name: "introduction"
            label: "Introduction Section"
            widget: "object"
            fields:
              - { name: "intro_title", label: "Intro Title", widget: "string" }
              - { name: "intro_paragraph", label: "Intro Paragraph", widget: "text" }
              - { name: "intro_card_title", label: "Intro Card Title", widget: "string" }
              - name: "intro_card_points"
                label: "Intro Card Points"
                widget: "object"
                fields:
                  - name: "points"
                    label: "Points"
                    widget: "list"
                    field: { label: "Point", name: "point", widget: "string" }
              - name: "intro_heading_two"
                label: "Secondary Heading Section"
                widget: "object"
                fields:
                  - { name: "intro_heading_two_title", label: "Heading Title", widget: "string" }
                  - name: "points"
                    label: "Points"
                    widget: "list"
                    fields:
                      - { name: "heading", label: "Heading", widget: "string" }
                      - { name: "subheading", label: "Subheading", widget: "text" }
              - { name: "button_title", label: "Button Title", widget: "string" }
              - { name: "image", label: "Image", widget: "image",choose_url: false, media_folder: "/static/uploads/projects_img", public_folder: "/uploads/projects_img" }
          - name: "how_it_works"
            label: "How It Works Section"
            widget: "object"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - name: "cards"
                label: "Cards"
                widget: "list"
                fields:
                  - { name: "number", label: "Number", widget: "number" }
                  - { name: "heading", label: "Heading", widget: "string" }
                  - { name: "subheading", label: "Subheading", widget: "text" }
          - name: "contact_us"
            label: "Contact Us Section"
            widget: "object"
            fields:
              - { name: "heading", label: "Heading", widget: "string" }
              - { name: "subheading", label: "Subheading", widget: "text" }
              - name: "cards"
                label: "Cards"
                widget: "list"
                fields:
                  - { name: "heading", label: "Heading", widget: "string" }
                  - { name: "subheading", label: " Subheading", widget: "string" }
                  - { name: "subheading2", label: "Other Detail", widget: "text" }
  - name: "project"
    label: "Project Page"
    files:
      - file: "content/project.md"
        label: "Project Page"
        name: "projectpage_content"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "date", label: "Date", widget: "datetime" }
          - { name: "draft", label: "Draft", widget: "boolean", default: false }
          - label: "Hero Section"
            name: "hero_section_group"
            widget: "object"
            fields:
              - { name: "home_button", label: "Home Button Text", widget: "string" }
              - { name: "heading", label: "Heading", widget: "string" }
              - { name: "subheading", label: "Sub Heading", widget: "string" }
              - { name: "schedule_meeting", label: "Primary Button text", widget: "string" }
              - { name: "call_button", label: "Secondary Button text", widget: "string" }
              - { name: "call_number", label: "Number to call", widget: "number" }
          - name: "Project_cards"
            label: "Project Cards"
            widget: "list"
            fields:
              - { name: "img_heading", label: "Image Heading", widget: "string" }
              - { name: "image", label: "Image", widget: "image", choose_url: false, media_folder: "/static/uploads/projects_img", public_folder: "/uploads/projects_img" }
              - { name: "heading", label: "Heading", widget: "string" }
              - { name: "location", label: "Location", widget: "string" }
              - { name: "date", label: "Date", widget: "string" }
              - { name: "description", label: "Description", widget: "text" }
              - { name: "inner_card_heading", label: "Inner Card Heading", widget: "string" }
              - { name: "inner_card_description", label: "Inner Card Description", widget: "text" }
              - { name: "review", label: "Review", widget: "text" }
          - name: "Result_section"
            label: "Result Section"
            widget: "object"
            fields:
              - { name: "heading", label: "Main Heading", widget: "string" }
              - { name: "total_projects", label: "Total Projects", widget: "string" }
              - { name: "prj_heading", label: "Projects Heading", widget: "string" }
              - { name: "rating", label: "Rating", widget: "number", step: 0.1 }
              - { name: "rating_heading", label: "Rating Heading", widget: "string" }
              - { name: "recommendation", label: "Recommendation %", widget: "number" }
              - { name: "rec_rate", label: "Recommendation Heading", widget: "string" }
              - { name: "experience", label: "Experience", widget: "string" }
              - { name: "exp_heading", label: "Experience Heading", widget: "string" }
          - name: "Review_section"
            label: "Review Section"
            widget: "object"
            fields:
              - { name: "main_heading", label: "Main Heading", widget: "string" }
              - name: "reviews"
                label: "Reviews"
                widget: "list"
                fields:
                  - { name: "review", label: "Review Text", widget: "text" }
                  - { name: "reviewed_by", label: "Reviewed By", widget: "string" }
          - name: "Final_cta"
            label: "Final Call To Action"
            widget: "object"
            fields:
              - { name: "heading", label: "Heading", widget: "string" }
              - { name: "description", label: "Description", widget: "text" }
              - { name: "schedule_meeting", label: "Schedule Meeting Button Text", widget: "string" }
              - { name: "call_button", label: "Call Button Text", widget: "string" }
              - { name: "call_number", label: "Call Number", widget: "string" }
  - name: "about-us"
    label: "About Us Page"
    file: "content/about-us.md"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "draft", label: "Draft", widget: "boolean", default: false }
      - { name: "type", label: "Type", widget: "string", default: "about-us" }
      - name: "hero_section_group"
        label: "Hero Section"
        widget: "object"
        fields:
          - { name: "home_button", label: "Home Button Text", widget: "string" }
          - { name: "hero_banner", label: "Hero Banner", widget: "image" ,choose_url: false, media_folder: "/static/uploads/about-us-img", public_folder: "/uploads/about-us-img" }
          - { name: "heading", label: "Heading", widget: "string" }
          - { name: "subheading", label: "Subheading", widget: "text" }
          - { name: "logo", label: "Logo", widget: "image" }
          - { name: "logo_heading", label: "Logo Heading", widget: "string" }
          - { name: "logo_subheading", label: "Logo Subheading", widget: "string" }
          - { name: "schedule_meeting", label: "Schedule Meeting Button Text", widget: "string" }
          - { name: "call_button", label: "Call Button Text", widget: "string" }
          - { name: "call_number", label: "Call Number", widget: "string" }


