baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Pareto E-commerce'

[menus]
  [[menus.main]]
    name = 'Diensten'
    identifier = 'services'
    weight = 20

  [[menus.main]]
    name = 'Kozijnen vervangen'
    pageRef = '/service/first'
    parent = 'services'
    weight = 21

  [[menus.main]]
    name = 'Gevelbekleding'
    pageRef = '/service/gevelbekleding'
    parent = 'services'
    weight = 22

  [[menus.main]]
    name = 'Dakkapel '
    pageRef = '/service/dakkapel'
    parent = 'services'
    weight = 23

  [[menus.main]]
    name = 'Schuifpuien'
    pageRef = '/service/schuifpuien'
    parent = 'services'
    weight = 24


  [[menus.main]]
    name = 'Over Ons'
    pageRef = '/about-us'
    weight = 30

  [[menus.main]]
    name = 'Projects'
    pageRef = '/project'
    weight = 40


[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
