baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Services'
    pageRef = '/service/first'
    weight = 20

  [[menus.main]]
    name = 'Services 2'
    pageRef = '/service/gevelbekleding'
    weight = 30

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 40

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 50

  

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
